stages:
  - test

cypress-e2e-test:
  stage: test
  image: cypress/browsers:node18.12.0-chrome103-ff107
  script:
    - echo "Running Cypress Tests"
    - npx cypress run --spec "cypress/e2e/todo.cy.js" --browser firefox
    - echo "Tests completed successfully."
  artifacts:
    paths:
      - cypress/screenshots/
      - cypress/videos/
    when: always