stages:
  - build
  - test

## Set environment variables for folders in "cache" job settings
## for npm modules and Cypress binary
variables:
  npm_config_cache: '$CI_PROJECT_DIR/.npm'
  CYPRESS_CACHE_FOLDER: '$CI_PROJECT_DIR/cache/Cypress'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cache/*
    - cache/Cypress
    - node_modules
    - build

## Install npm dependencies and Cypress
install:
  image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
  stage: build
  script:
    - npm ci

cypress-e2e-test:
  image: 
    name: cypress/browsers:node18.12.0-chrome103-ff107 
    entrypoint: [""]
  stage: test
  script:
    - npm ci
    - mkdir -p cypress/  # Asegurarse de que el directorio cypress/ exista
    - npm start &
    - ls -R cypress/e2e  # Verificar los archivos en la ruta
    - npx cypress run --spec "cypress/e2e/todo.cy.js" --browser chrome
  allow_failure: true   # Permite que el trabajo falle sin afectar el pipeline
  artifacts:
    paths: 
      - cypress/
    when: always
  only:
    - main